### ISSUE TITLE
Why both ERC721 and ERC20 ?

### ISSUE THREAD

**Issue by gotjoshua** [Uniswap/unisocks#3]
When investigating the code i don't manage to figure out what the ERC721 and ERC20 are used for specifically in this scenario.  Can anyone explain that?

It seems that the contract on etherscan is an ERC20, and as far as I know Uniswap only works with ERC20, but there is something going on with ERC721...

**Comment by yakobsoahmin00** [comment]
https://github.com/Uniswap/unisocks/issues/3#issue-771365863
