### ISSUE TITLE
Hi can you tell us how you set up your database schema for fauna db for SOCKS?

### ISSUE THREAD

**Issue by ChristopherDuVall** [Uniswap/unisocks#6]
Hi can you tell us how you set up your database schema for fauna db for SOCKS?

Working on a project and we haven't been able to figure out. 

Best,
Chris

**Comment by ChristopherDuVall** [comment]
probably would be better to message and not create an issue for this.

**Comment by N9SHazpnhYW** [comment]
Any chance you got an answer to this question?
